### ISSUE TITLE
The way we configure ledgers is redundant and we don't validate on whether it is correct

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1455]
Currently, the configuration file contains, among other things, the following:

```toml
[bitcoin]
network = "regtest"
node_url = "http://localhost:18443"

[ethereum]
network = "regtest"
node_url = "http://localhost:8545"
```

**Problem:** This is redundant + we don't validate whether it is actually true (i.e. whether the node at `localhost:8545` is actually a regtest node).

**Goal:**
1. Provide a non-redunant and easy to configure way of which ledgers the software should connect to.
2. Validate, which ledgers we are connecting to.

**Recommendation:**

1. The sections should be optional (I think this is already the case)
2. When specified, the minimum should be to specify a network. Given a network, the software should:
- for Bitcoin, always use the bitcoind connector
- for Ethereum, always use the web3 connector

Further customization is purposely deferred to the future to not over-complicate the configuration. Once the p2p connectors (https://github.com/comit-network/comit-rs/issues/1250, https://github.com/comit-network/comit-rs/issues/1409) are implemented, we will have to think of a useful, yet simple way to configure these.
